/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl.vtk.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.january.geometry.dsl.vtk.parser.antlr.internal.InternalVTKParser;
import org.eclipse.january.geometry.dsl.vtk.services.VTKGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class VTKParser extends AbstractAntlrParser {

	@Inject
	private VTKGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_SL_COMMENT", "RULE_WS");
	}
	

	@Override
	protected InternalVTKParser createParser(XtextTokenStream stream) {
		return new InternalVTKParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Geometry";
	}

	public VTKGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VTKGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
