/**
 *
 * $Id$
 */
package geometry.validation;

import geometry.NamedNode;
import geometry.Shape;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link geometry.Geometry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GeometryValidator {
	boolean validate();

	boolean validateNodes(EList<NamedNode> value);

	boolean validateShapes(EList<Shape> value);
	boolean validateName(String value);
}
