/**
 *
 * $Id$
 */
package geometry.validation;

import geometry.INode;
import geometry.Triangle;
import geometry.Vertex;
import org.eclipse.emf.common.util.EList;


/**
 * A sample validator interface for {@link geometry.INode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface INodeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateId(long value);

	boolean validateNodes(EList<INode> value);

	boolean validateType(String value);

	boolean validateTriangles(EList<Triangle> value);

	boolean validateCenter(Vertex value);

}
