/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl.vtk.ui.tests;

import com.google.inject.Injector;
import org.eclipse.january.geometry.dsl.vtk.ui.internal.VtkActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class VTKUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VtkActivator.getInstance().getInjector("org.eclipse.january.geometry.dsl.vtk.VTK");
	}

}
