sudo: false # use containers

language: java

# Makes build faster to cache maven things.
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
services:
  - docker

jdk:
 - openjdk8

# don't do anything on install, just let maven install the dependencies in the script
# Also see https://github.com/eclipse/january/issues/109
install:
  - true
  
# verify does everything, including tests, but excludes the install step
script: 
 - mvn verify

# display log to debug build
after_failure:
 - for i in /home/travis/build/eclipse/january/org.eclipse.january*/target/work/configuration/*.log; do
     echo $i;
     cat $i;
   done

