/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.january.geometry.xtext.obj.ui.internal.ObjActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OBJExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ObjActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ObjActivator.getInstance().getInjector(ObjActivator.ORG_ECLIPSE_JANUARY_GEOMETRY_XTEXT_OBJ);
	}
	
}
