/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl;

import com.google.inject.Binder;
import com.google.inject.name.Names;
import org.eclipse.january.geometry.dsl.AbstractIGESRuntimeModule;
import org.eclipse.january.geometry.dsl.CustomIGESLexer;
import org.eclipse.january.geometry.dsl.IGESTerminalConverters;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.parser.antlr.Lexer;
import org.eclipse.xtext.parser.antlr.LexerBindings;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IGESRuntimeModule extends AbstractIGESRuntimeModule {
  @Override
  public void configureRuntimeLexer(final Binder binder) {
    binder.<Lexer>bind(Lexer.class).annotatedWith(Names.named(LexerBindings.RUNTIME)).to(CustomIGESLexer.class);
  }
  
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return IGESTerminalConverters.class;
  }
}
