/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EValidator;
import org.eclipse.emf.ecore.impl.EValidatorRegistryImpl;
import org.eclipse.january.geometry.dsl.AbstractOBJRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OBJRuntimeModule extends AbstractOBJRuntimeModule {
  @Override
  public EValidator.Registry bindEValidatorRegistry() {
    return new EValidatorRegistryImpl() {
      @Override
      public Object get(final Object key) {
        return null;
      }
      
      @Override
      public EValidator getEValidator(final EPackage ePackage) {
        return null;
      }
    };
  }
}
