/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl.tests;

import com.google.inject.Inject;
import org.eclipse.january.geometry.dsl.iGES.IGES;
import org.eclipse.january.geometry.dsl.tests.IGESInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;

@Ignore
@RunWith(XtextRunner.class)
@InjectWith(IGESInjectorProvider.class)
@SuppressWarnings("all")
public class IGESParsingTest {
  @Inject
  private ParseHelper<IGES> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final IGES result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
