/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OBJAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/january/geometry/xtext/parser/antlr/internal/InternalOBJ.tokens");
	}
}
