/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl.vtk.validation;

import org.eclipse.january.geometry.dsl.vtk.validation.AbstractVTKValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VTKValidator extends AbstractVTKValidator {
}
