/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.january.geometry.xtext.services.OBJGrammarAccess;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class OBJSyntacticSequencer extends AbstractSyntacticSequencer {

	protected OBJGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Face___SolidusKeyword_1_1_0_SolidusKeyword_1_1_1_2_0_EIntParserRuleCall_1_1_1_2_1__q;
	protected AbstractElementAlias match_PolyShape_GKeyword_2_0_q;
	protected AbstractElementAlias match_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____a;
	protected AbstractElementAlias match_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____p;
	protected AbstractElementAlias match_VertexSource___GKeyword_2_0_EStringParserRuleCall_2_1_q__q;
	protected AbstractElementAlias match_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__a;
	protected AbstractElementAlias match_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (OBJGrammarAccess) access;
		match_Face___SolidusKeyword_1_1_0_SolidusKeyword_1_1_1_2_0_EIntParserRuleCall_1_1_1_2_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFaceAccess().getSolidusKeyword_1_1_0()), new TokenAlias(false, false, grammarAccess.getFaceAccess().getSolidusKeyword_1_1_1_2_0()), new TokenAlias(false, false, grammarAccess.getFaceAccess().getEIntParserRuleCall_1_1_1_2_1()));
		match_PolyShape_GKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getPolyShapeAccess().getGKeyword_2_0());
		match_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getPolyShapeAccess().getSKeyword_4_1_0()), new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getPolyShapeAccess().getEIntParserRuleCall_4_1_1_0()), new TokenAlias(false, false, grammarAccess.getPolyShapeAccess().getOffKeyword_4_1_1_1())));
		match_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____p = new GroupAlias(true, false, new TokenAlias(false, false, grammarAccess.getPolyShapeAccess().getSKeyword_4_1_0()), new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getPolyShapeAccess().getEIntParserRuleCall_4_1_1_0()), new TokenAlias(false, false, grammarAccess.getPolyShapeAccess().getOffKeyword_4_1_1_1())));
		match_VertexSource___GKeyword_2_0_EStringParserRuleCall_2_1_q__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getGKeyword_2_0()), new TokenAlias(false, true, grammarAccess.getVertexSourceAccess().getEStringParserRuleCall_2_1()));
		match_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getVnKeyword_3_2_0()), new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getEDoubleParserRuleCall_3_2_1()), new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getEDoubleParserRuleCall_3_2_2()), new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getEDoubleParserRuleCall_3_2_3()));
		match_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__p = new GroupAlias(true, false, new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getVnKeyword_3_2_0()), new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getEDoubleParserRuleCall_3_2_1()), new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getEDoubleParserRuleCall_3_2_2()), new TokenAlias(false, false, grammarAccess.getVertexSourceAccess().getEDoubleParserRuleCall_3_2_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getEDoubleRule())
			return getEDoubleToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEIntRule())
			return getEIntToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEStringRule())
			return getEStringToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * EDouble returns ecore::EDouble:
	 * 	DOUBLE |  EInt
	 * ;
	 */
	protected String getEDoubleToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ".";
	}
	
	/**
	 * EInt returns ecore::EInt:
	 * 	'-'? INT
	 * ;
	 */
	protected String getEIntToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * EString returns ecore::EString:
	 * 	(STRING | ID | INT | '.' | '/' | '\\' | ':' | '_' | '-' )+
	 * ;
	 */
	protected String getEStringToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\"\"";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Face___SolidusKeyword_1_1_0_SolidusKeyword_1_1_1_2_0_EIntParserRuleCall_1_1_1_2_1__q.equals(syntax))
				emit_Face___SolidusKeyword_1_1_0_SolidusKeyword_1_1_1_2_0_EIntParserRuleCall_1_1_1_2_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PolyShape_GKeyword_2_0_q.equals(syntax))
				emit_PolyShape_GKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____a.equals(syntax))
				emit_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____p.equals(syntax))
				emit_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VertexSource___GKeyword_2_0_EStringParserRuleCall_2_1_q__q.equals(syntax))
				emit_VertexSource___GKeyword_2_0_EStringParserRuleCall_2_1_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__a.equals(syntax))
				emit_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__p.equals(syntax))
				emit_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('/' '/' EInt)?
	 *
	 * This ambiguous syntax occurs at:
	 *     vertexIndices+=EInt (ambiguity) (rule end)
	 *     vertexIndices+=EInt (ambiguity) vertexIndices+=EInt
	 */
	protected void emit_Face___SolidusKeyword_1_1_0_SolidusKeyword_1_1_1_2_0_EIntParserRuleCall_1_1_1_2_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'g'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'usemtl' material=Material
	 *     (rule start) (ambiguity) ('s' (EInt | 'off'))* 'f' faces+=Face
	 *     (rule start) (ambiguity) ('s' (EInt | 'off'))+ (rule start)
	 *     materialFiles+=EString (ambiguity) 'usemtl' material=Material
	 *     materialFiles+=EString (ambiguity) ('s' (EInt | 'off'))* 'f' faces+=Face
	 *     materialFiles+=EString (ambiguity) ('s' (EInt | 'off'))+ (rule end)
	 */
	protected void emit_PolyShape_GKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('s' (EInt | 'off'))*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'g'? (ambiguity) 'f' faces+=Face
	 *     faces+=Face (ambiguity) 'f' faces+=Face
	 *     faces+=Face (ambiguity) (rule end)
	 *     material=Material (ambiguity) 'f' faces+=Face
	 *     materialFiles+=EString 'g'? (ambiguity) 'f' faces+=Face
	 *     name=EString (ambiguity) 'f' faces+=Face
	 */
	protected void emit_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('s' (EInt | 'off'))+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'g'? (ambiguity) (rule start)
	 *     material=Material (ambiguity) (rule end)
	 *     materialFiles+=EString 'g'? (ambiguity) (rule end)
	 *     name=EString (ambiguity) (rule end)
	 */
	protected void emit_PolyShape___SKeyword_4_1_0___EIntParserRuleCall_4_1_1_0_or_OffKeyword_4_1_1_1____p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('g' EString?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ('vn' EDouble EDouble EDouble)* 'v' vertices+=Vertex
	 *     (rule start) (ambiguity) ('vn' EDouble EDouble EDouble)* 'vt' textureCoordinates+=TextureVertex
	 *     (rule start) (ambiguity) ('vn' EDouble EDouble EDouble)+ (rule start)
	 *     materialFiles+=EString (ambiguity) ('vn' EDouble EDouble EDouble)* 'v' vertices+=Vertex
	 *     materialFiles+=EString (ambiguity) ('vn' EDouble EDouble EDouble)* 'vt' textureCoordinates+=TextureVertex
	 *     materialFiles+=EString (ambiguity) ('vn' EDouble EDouble EDouble)+ (rule end)
	 */
	protected void emit_VertexSource___GKeyword_2_0_EStringParserRuleCall_2_1_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('vn' EDouble EDouble EDouble)*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) ('g' EString?)? (ambiguity) 'v' vertices+=Vertex
	 *     (rule start) ('g' EString?)? (ambiguity) 'vt' textureCoordinates+=TextureVertex
	 *     materialFiles+=EString ('g' EString?)? (ambiguity) 'v' vertices+=Vertex
	 *     materialFiles+=EString ('g' EString?)? (ambiguity) 'vt' textureCoordinates+=TextureVertex
	 *     textureCoordinates+=TextureVertex (ambiguity) 'v' vertices+=Vertex
	 *     textureCoordinates+=TextureVertex (ambiguity) 'vt' textureCoordinates+=TextureVertex
	 *     textureCoordinates+=TextureVertex (ambiguity) (rule end)
	 *     vertices+=Vertex (ambiguity) 'v' vertices+=Vertex
	 *     vertices+=Vertex (ambiguity) 'vt' textureCoordinates+=TextureVertex
	 *     vertices+=Vertex (ambiguity) (rule end)
	 */
	protected void emit_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('vn' EDouble EDouble EDouble)+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) ('g' EString?)? (ambiguity) (rule start)
	 *     materialFiles+=EString ('g' EString?)? (ambiguity) (rule end)
	 */
	protected void emit_VertexSource___VnKeyword_3_2_0_EDoubleParserRuleCall_3_2_1_EDoubleParserRuleCall_3_2_2_EDoubleParserRuleCall_3_2_3__p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
