/**
 *
 * $Id$
 */
package org.eclipse.january.geometry.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.january.geometry.INode;
import org.eclipse.january.geometry.Triangle;
import org.eclipse.january.geometry.Vertex;

/**
 * A sample validator interface for {@link org.eclipse.january.geometry.INode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface INodeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateId(long value);
	boolean validateNodes(EList<INode> value);
	boolean validateType(String value);
	boolean validateTriangles(EList<Triangle> value);
	boolean validateCenter(Vertex value);
	boolean validateParent(INode value);
}
