/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl.iGES;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.End#getSval <em>Sval</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.End#getGval <em>Gval</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.End#getDval <em>Dval</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.End#getPval <em>Pval</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.End#getTval <em>Tval</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEnd()
 * @model
 * @generated
 */
public interface End extends EObject
{
  /**
   * Returns the value of the '<em><b>Sval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sval</em>' attribute.
   * @see #setSval(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEnd_Sval()
   * @model
   * @generated
   */
  int getSval();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.End#getSval <em>Sval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sval</em>' attribute.
   * @see #getSval()
   * @generated
   */
  void setSval(int value);

  /**
   * Returns the value of the '<em><b>Gval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gval</em>' attribute.
   * @see #setGval(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEnd_Gval()
   * @model
   * @generated
   */
  int getGval();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.End#getGval <em>Gval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gval</em>' attribute.
   * @see #getGval()
   * @generated
   */
  void setGval(int value);

  /**
   * Returns the value of the '<em><b>Dval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dval</em>' attribute.
   * @see #setDval(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEnd_Dval()
   * @model
   * @generated
   */
  int getDval();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.End#getDval <em>Dval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dval</em>' attribute.
   * @see #getDval()
   * @generated
   */
  void setDval(int value);

  /**
   * Returns the value of the '<em><b>Pval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pval</em>' attribute.
   * @see #setPval(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEnd_Pval()
   * @model
   * @generated
   */
  int getPval();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.End#getPval <em>Pval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pval</em>' attribute.
   * @see #getPval()
   * @generated
   */
  void setPval(int value);

  /**
   * Returns the value of the '<em><b>Tval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tval</em>' attribute.
   * @see #setTval(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEnd_Tval()
   * @model
   * @generated
   */
  int getTval();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.End#getTval <em>Tval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tval</em>' attribute.
   * @see #getTval()
   * @generated
   */
  void setTval(int value);

} // End
