/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl.iGES;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getType <em>Type</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getParamData <em>Param Data</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getStructure <em>Structure</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getLineFont <em>Line Font</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getLevel <em>Level</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getView <em>View</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getTransformMatrix <em>Transform Matrix</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getStatus <em>Status</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getIndex <em>Index</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getLineWeight <em>Line Weight</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getColor <em>Color</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getParamLines <em>Param Lines</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getForm <em>Form</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getEntityLabel <em>Entity Label</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Entry#getSubNum <em>Sub Num</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry()
 * @model
 * @generated
 */
public interface Entry extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_Type()
   * @model
   * @generated
   */
  int getType();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(int value);

  /**
   * Returns the value of the '<em><b>Param Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param Data</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Data</em>' attribute.
   * @see #setParamData(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_ParamData()
   * @model
   * @generated
   */
  int getParamData();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getParamData <em>Param Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Data</em>' attribute.
   * @see #getParamData()
   * @generated
   */
  void setParamData(int value);

  /**
   * Returns the value of the '<em><b>Structure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Structure</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structure</em>' attribute.
   * @see #setStructure(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_Structure()
   * @model
   * @generated
   */
  int getStructure();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getStructure <em>Structure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Structure</em>' attribute.
   * @see #getStructure()
   * @generated
   */
  void setStructure(int value);

  /**
   * Returns the value of the '<em><b>Line Font</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Line Font</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line Font</em>' attribute.
   * @see #setLineFont(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_LineFont()
   * @model
   * @generated
   */
  int getLineFont();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getLineFont <em>Line Font</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Line Font</em>' attribute.
   * @see #getLineFont()
   * @generated
   */
  void setLineFont(int value);

  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Level</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see #setLevel(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_Level()
   * @model
   * @generated
   */
  int getLevel();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see #getLevel()
   * @generated
   */
  void setLevel(int value);

  /**
   * Returns the value of the '<em><b>View</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>View</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>View</em>' attribute.
   * @see #setView(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_View()
   * @model
   * @generated
   */
  int getView();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getView <em>View</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>View</em>' attribute.
   * @see #getView()
   * @generated
   */
  void setView(int value);

  /**
   * Returns the value of the '<em><b>Transform Matrix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transform Matrix</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transform Matrix</em>' attribute.
   * @see #setTransformMatrix(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_TransformMatrix()
   * @model
   * @generated
   */
  int getTransformMatrix();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getTransformMatrix <em>Transform Matrix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transform Matrix</em>' attribute.
   * @see #getTransformMatrix()
   * @generated
   */
  void setTransformMatrix(int value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Status</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see #setStatus(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_Status()
   * @model
   * @generated
   */
  int getStatus();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see #getStatus()
   * @generated
   */
  void setStatus(int value);

  /**
   * Returns the value of the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Index</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' attribute.
   * @see #setIndex(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_Index()
   * @model
   * @generated
   */
  int getIndex();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getIndex <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' attribute.
   * @see #getIndex()
   * @generated
   */
  void setIndex(int value);

  /**
   * Returns the value of the '<em><b>Line Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Line Weight</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line Weight</em>' attribute.
   * @see #setLineWeight(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_LineWeight()
   * @model
   * @generated
   */
  int getLineWeight();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getLineWeight <em>Line Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Line Weight</em>' attribute.
   * @see #getLineWeight()
   * @generated
   */
  void setLineWeight(int value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see #setColor(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_Color()
   * @model
   * @generated
   */
  int getColor();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see #getColor()
   * @generated
   */
  void setColor(int value);

  /**
   * Returns the value of the '<em><b>Param Lines</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param Lines</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Lines</em>' attribute.
   * @see #setParamLines(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_ParamLines()
   * @model
   * @generated
   */
  int getParamLines();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getParamLines <em>Param Lines</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Lines</em>' attribute.
   * @see #getParamLines()
   * @generated
   */
  void setParamLines(int value);

  /**
   * Returns the value of the '<em><b>Form</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Form</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Form</em>' attribute.
   * @see #setForm(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_Form()
   * @model
   * @generated
   */
  int getForm();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getForm <em>Form</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Form</em>' attribute.
   * @see #getForm()
   * @generated
   */
  void setForm(int value);

  /**
   * Returns the value of the '<em><b>Entity Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity Label</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Label</em>' attribute.
   * @see #setEntityLabel(String)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_EntityLabel()
   * @model
   * @generated
   */
  String getEntityLabel();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getEntityLabel <em>Entity Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Label</em>' attribute.
   * @see #getEntityLabel()
   * @generated
   */
  void setEntityLabel(String value);

  /**
   * Returns the value of the '<em><b>Sub Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sub Num</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Num</em>' attribute.
   * @see #setSubNum(int)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getEntry_SubNum()
   * @model
   * @generated
   */
  int getSubNum();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Entry#getSubNum <em>Sub Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Num</em>' attribute.
   * @see #getSubNum()
   * @generated
   */
  void setSubNum(int value);

} // Entry
