/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl.iGES;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.Param#getVal <em>Val</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getParam()
 * @model
 * @generated
 */
public interface Param extends Value
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(double)
   * @see org.eclipse.january.geometry.dsl.iGES.IGESPackage#getParam_Val()
   * @model
   * @generated
   */
  double getVal();

  /**
   * Sets the value of the '{@link org.eclipse.january.geometry.dsl.iGES.Param#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(double value);

} // Param
