/**
 *
 * $Id$
 */
package org.eclipse.january.geometry.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.january.geometry.Vertex;

/**
 * A sample validator interface for {@link org.eclipse.january.geometry.VertexSource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VertexSourceValidator {
	boolean validate();

	boolean validateVertices(EList<Vertex> value);
	boolean validateTextureCoordinates(EList<Vertex> value);

	boolean validateMaterialFiles(EList<String> value);
}
