/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.dsl.iGES.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import org.eclipse.january.geometry.dsl.iGES.Entry;
import org.eclipse.january.geometry.dsl.iGES.IGESPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entry</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getParamData <em>Param Data</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getStructure <em>Structure</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getLineFont <em>Line Font</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getLevel <em>Level</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getView <em>View</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getTransformMatrix <em>Transform Matrix</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getStatus <em>Status</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getIndex <em>Index</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getLineWeight <em>Line Weight</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getColor <em>Color</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getParamLines <em>Param Lines</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getForm <em>Form</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getEntityLabel <em>Entity Label</em>}</li>
 *   <li>{@link org.eclipse.january.geometry.dsl.iGES.impl.EntryImpl#getSubNum <em>Sub Num</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class EntryImpl extends MinimalEObjectImpl.Container implements Entry
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final int TYPE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected int type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getParamData() <em>Param Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParamData()
   * @generated
   * @ordered
   */
  protected static final int PARAM_DATA_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getParamData() <em>Param Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParamData()
   * @generated
   * @ordered
   */
  protected int paramData = PARAM_DATA_EDEFAULT;

  /**
   * The default value of the '{@link #getStructure() <em>Structure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructure()
   * @generated
   * @ordered
   */
  protected static final int STRUCTURE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStructure() <em>Structure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructure()
   * @generated
   * @ordered
   */
  protected int structure = STRUCTURE_EDEFAULT;

  /**
   * The default value of the '{@link #getLineFont() <em>Line Font</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineFont()
   * @generated
   * @ordered
   */
  protected static final int LINE_FONT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLineFont() <em>Line Font</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineFont()
   * @generated
   * @ordered
   */
  protected int lineFont = LINE_FONT_EDEFAULT;

  /**
   * The default value of the '{@link #getLevel() <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevel()
   * @generated
   * @ordered
   */
  protected static final int LEVEL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLevel() <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevel()
   * @generated
   * @ordered
   */
  protected int level = LEVEL_EDEFAULT;

  /**
   * The default value of the '{@link #getView() <em>View</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getView()
   * @generated
   * @ordered
   */
  protected static final int VIEW_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getView() <em>View</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getView()
   * @generated
   * @ordered
   */
  protected int view = VIEW_EDEFAULT;

  /**
   * The default value of the '{@link #getTransformMatrix() <em>Transform Matrix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransformMatrix()
   * @generated
   * @ordered
   */
  protected static final int TRANSFORM_MATRIX_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTransformMatrix() <em>Transform Matrix</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransformMatrix()
   * @generated
   * @ordered
   */
  protected int transformMatrix = TRANSFORM_MATRIX_EDEFAULT;

  /**
   * The default value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected static final int STATUS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected int status = STATUS_EDEFAULT;

  /**
   * The default value of the '{@link #getIndex() <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndex()
   * @generated
   * @ordered
   */
  protected static final int INDEX_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIndex() <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndex()
   * @generated
   * @ordered
   */
  protected int index = INDEX_EDEFAULT;

  /**
   * The default value of the '{@link #getLineWeight() <em>Line Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineWeight()
   * @generated
   * @ordered
   */
  protected static final int LINE_WEIGHT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLineWeight() <em>Line Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineWeight()
   * @generated
   * @ordered
   */
  protected int lineWeight = LINE_WEIGHT_EDEFAULT;

  /**
   * The default value of the '{@link #getColor() <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected static final int COLOR_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getColor() <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected int color = COLOR_EDEFAULT;

  /**
   * The default value of the '{@link #getParamLines() <em>Param Lines</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParamLines()
   * @generated
   * @ordered
   */
  protected static final int PARAM_LINES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getParamLines() <em>Param Lines</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParamLines()
   * @generated
   * @ordered
   */
  protected int paramLines = PARAM_LINES_EDEFAULT;

  /**
   * The default value of the '{@link #getForm() <em>Form</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForm()
   * @generated
   * @ordered
   */
  protected static final int FORM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getForm() <em>Form</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForm()
   * @generated
   * @ordered
   */
  protected int form = FORM_EDEFAULT;

  /**
   * The default value of the '{@link #getEntityLabel() <em>Entity Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntityLabel()
   * @generated
   * @ordered
   */
  protected static final String ENTITY_LABEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEntityLabel() <em>Entity Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntityLabel()
   * @generated
   * @ordered
   */
  protected String entityLabel = ENTITY_LABEL_EDEFAULT;

  /**
   * The default value of the '{@link #getSubNum() <em>Sub Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubNum()
   * @generated
   * @ordered
   */
  protected static final int SUB_NUM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSubNum() <em>Sub Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubNum()
   * @generated
   * @ordered
   */
  protected int subNum = SUB_NUM_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IGESPackage.Literals.ENTRY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(int newType)
  {
    int oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getParamData()
  {
    return paramData;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParamData(int newParamData)
  {
    int oldParamData = paramData;
    paramData = newParamData;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__PARAM_DATA, oldParamData, paramData));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getStructure()
  {
    return structure;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStructure(int newStructure)
  {
    int oldStructure = structure;
    structure = newStructure;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__STRUCTURE, oldStructure, structure));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLineFont()
  {
    return lineFont;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLineFont(int newLineFont)
  {
    int oldLineFont = lineFont;
    lineFont = newLineFont;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__LINE_FONT, oldLineFont, lineFont));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLevel()
  {
    return level;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLevel(int newLevel)
  {
    int oldLevel = level;
    level = newLevel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__LEVEL, oldLevel, level));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getView()
  {
    return view;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setView(int newView)
  {
    int oldView = view;
    view = newView;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__VIEW, oldView, view));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTransformMatrix()
  {
    return transformMatrix;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTransformMatrix(int newTransformMatrix)
  {
    int oldTransformMatrix = transformMatrix;
    transformMatrix = newTransformMatrix;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__TRANSFORM_MATRIX, oldTransformMatrix, transformMatrix));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getStatus()
  {
    return status;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStatus(int newStatus)
  {
    int oldStatus = status;
    status = newStatus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__STATUS, oldStatus, status));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getIndex()
  {
    return index;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIndex(int newIndex)
  {
    int oldIndex = index;
    index = newIndex;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__INDEX, oldIndex, index));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLineWeight()
  {
    return lineWeight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLineWeight(int newLineWeight)
  {
    int oldLineWeight = lineWeight;
    lineWeight = newLineWeight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__LINE_WEIGHT, oldLineWeight, lineWeight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getColor()
  {
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setColor(int newColor)
  {
    int oldColor = color;
    color = newColor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__COLOR, oldColor, color));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getParamLines()
  {
    return paramLines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParamLines(int newParamLines)
  {
    int oldParamLines = paramLines;
    paramLines = newParamLines;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__PARAM_LINES, oldParamLines, paramLines));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getForm()
  {
    return form;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setForm(int newForm)
  {
    int oldForm = form;
    form = newForm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__FORM, oldForm, form));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEntityLabel()
  {
    return entityLabel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEntityLabel(String newEntityLabel)
  {
    String oldEntityLabel = entityLabel;
    entityLabel = newEntityLabel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__ENTITY_LABEL, oldEntityLabel, entityLabel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSubNum()
  {
    return subNum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSubNum(int newSubNum)
  {
    int oldSubNum = subNum;
    subNum = newSubNum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IGESPackage.ENTRY__SUB_NUM, oldSubNum, subNum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IGESPackage.ENTRY__TYPE:
        return getType();
      case IGESPackage.ENTRY__PARAM_DATA:
        return getParamData();
      case IGESPackage.ENTRY__STRUCTURE:
        return getStructure();
      case IGESPackage.ENTRY__LINE_FONT:
        return getLineFont();
      case IGESPackage.ENTRY__LEVEL:
        return getLevel();
      case IGESPackage.ENTRY__VIEW:
        return getView();
      case IGESPackage.ENTRY__TRANSFORM_MATRIX:
        return getTransformMatrix();
      case IGESPackage.ENTRY__STATUS:
        return getStatus();
      case IGESPackage.ENTRY__INDEX:
        return getIndex();
      case IGESPackage.ENTRY__LINE_WEIGHT:
        return getLineWeight();
      case IGESPackage.ENTRY__COLOR:
        return getColor();
      case IGESPackage.ENTRY__PARAM_LINES:
        return getParamLines();
      case IGESPackage.ENTRY__FORM:
        return getForm();
      case IGESPackage.ENTRY__ENTITY_LABEL:
        return getEntityLabel();
      case IGESPackage.ENTRY__SUB_NUM:
        return getSubNum();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IGESPackage.ENTRY__TYPE:
        setType((Integer)newValue);
        return;
      case IGESPackage.ENTRY__PARAM_DATA:
        setParamData((Integer)newValue);
        return;
      case IGESPackage.ENTRY__STRUCTURE:
        setStructure((Integer)newValue);
        return;
      case IGESPackage.ENTRY__LINE_FONT:
        setLineFont((Integer)newValue);
        return;
      case IGESPackage.ENTRY__LEVEL:
        setLevel((Integer)newValue);
        return;
      case IGESPackage.ENTRY__VIEW:
        setView((Integer)newValue);
        return;
      case IGESPackage.ENTRY__TRANSFORM_MATRIX:
        setTransformMatrix((Integer)newValue);
        return;
      case IGESPackage.ENTRY__STATUS:
        setStatus((Integer)newValue);
        return;
      case IGESPackage.ENTRY__INDEX:
        setIndex((Integer)newValue);
        return;
      case IGESPackage.ENTRY__LINE_WEIGHT:
        setLineWeight((Integer)newValue);
        return;
      case IGESPackage.ENTRY__COLOR:
        setColor((Integer)newValue);
        return;
      case IGESPackage.ENTRY__PARAM_LINES:
        setParamLines((Integer)newValue);
        return;
      case IGESPackage.ENTRY__FORM:
        setForm((Integer)newValue);
        return;
      case IGESPackage.ENTRY__ENTITY_LABEL:
        setEntityLabel((String)newValue);
        return;
      case IGESPackage.ENTRY__SUB_NUM:
        setSubNum((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IGESPackage.ENTRY__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case IGESPackage.ENTRY__PARAM_DATA:
        setParamData(PARAM_DATA_EDEFAULT);
        return;
      case IGESPackage.ENTRY__STRUCTURE:
        setStructure(STRUCTURE_EDEFAULT);
        return;
      case IGESPackage.ENTRY__LINE_FONT:
        setLineFont(LINE_FONT_EDEFAULT);
        return;
      case IGESPackage.ENTRY__LEVEL:
        setLevel(LEVEL_EDEFAULT);
        return;
      case IGESPackage.ENTRY__VIEW:
        setView(VIEW_EDEFAULT);
        return;
      case IGESPackage.ENTRY__TRANSFORM_MATRIX:
        setTransformMatrix(TRANSFORM_MATRIX_EDEFAULT);
        return;
      case IGESPackage.ENTRY__STATUS:
        setStatus(STATUS_EDEFAULT);
        return;
      case IGESPackage.ENTRY__INDEX:
        setIndex(INDEX_EDEFAULT);
        return;
      case IGESPackage.ENTRY__LINE_WEIGHT:
        setLineWeight(LINE_WEIGHT_EDEFAULT);
        return;
      case IGESPackage.ENTRY__COLOR:
        setColor(COLOR_EDEFAULT);
        return;
      case IGESPackage.ENTRY__PARAM_LINES:
        setParamLines(PARAM_LINES_EDEFAULT);
        return;
      case IGESPackage.ENTRY__FORM:
        setForm(FORM_EDEFAULT);
        return;
      case IGESPackage.ENTRY__ENTITY_LABEL:
        setEntityLabel(ENTITY_LABEL_EDEFAULT);
        return;
      case IGESPackage.ENTRY__SUB_NUM:
        setSubNum(SUB_NUM_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IGESPackage.ENTRY__TYPE:
        return type != TYPE_EDEFAULT;
      case IGESPackage.ENTRY__PARAM_DATA:
        return paramData != PARAM_DATA_EDEFAULT;
      case IGESPackage.ENTRY__STRUCTURE:
        return structure != STRUCTURE_EDEFAULT;
      case IGESPackage.ENTRY__LINE_FONT:
        return lineFont != LINE_FONT_EDEFAULT;
      case IGESPackage.ENTRY__LEVEL:
        return level != LEVEL_EDEFAULT;
      case IGESPackage.ENTRY__VIEW:
        return view != VIEW_EDEFAULT;
      case IGESPackage.ENTRY__TRANSFORM_MATRIX:
        return transformMatrix != TRANSFORM_MATRIX_EDEFAULT;
      case IGESPackage.ENTRY__STATUS:
        return status != STATUS_EDEFAULT;
      case IGESPackage.ENTRY__INDEX:
        return index != INDEX_EDEFAULT;
      case IGESPackage.ENTRY__LINE_WEIGHT:
        return lineWeight != LINE_WEIGHT_EDEFAULT;
      case IGESPackage.ENTRY__COLOR:
        return color != COLOR_EDEFAULT;
      case IGESPackage.ENTRY__PARAM_LINES:
        return paramLines != PARAM_LINES_EDEFAULT;
      case IGESPackage.ENTRY__FORM:
        return form != FORM_EDEFAULT;
      case IGESPackage.ENTRY__ENTITY_LABEL:
        return ENTITY_LABEL_EDEFAULT == null ? entityLabel != null : !ENTITY_LABEL_EDEFAULT.equals(entityLabel);
      case IGESPackage.ENTRY__SUB_NUM:
        return subNum != SUB_NUM_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", paramData: ");
    result.append(paramData);
    result.append(", structure: ");
    result.append(structure);
    result.append(", lineFont: ");
    result.append(lineFont);
    result.append(", level: ");
    result.append(level);
    result.append(", view: ");
    result.append(view);
    result.append(", TransformMatrix: ");
    result.append(transformMatrix);
    result.append(", status: ");
    result.append(status);
    result.append(", index: ");
    result.append(index);
    result.append(", lineWeight: ");
    result.append(lineWeight);
    result.append(", color: ");
    result.append(color);
    result.append(", paramLines: ");
    result.append(paramLines);
    result.append(", form: ");
    result.append(form);
    result.append(", entityLabel: ");
    result.append(entityLabel);
    result.append(", subNum: ");
    result.append(subNum);
    result.append(')');
    return result.toString();
  }

} //EntryImpl
